import type { Metadata } from "next";
import "./globals.css";
import { BODY_FONT } from "@/lib/font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${BODY_FONT.className} antialiased`}>
        <div>{children}</div>
      </body>
    </html>
  );
}
